### ISSUE TITLE
Can't generate schema from db

### ISSUE THREAD

**Issue by mongris** [Lantern-chat/thorn#3]
I was searching for Rust ORM libraries and came across your answer. I tried learning how to use `thorn` from the `Lantern chat`, but I encountered an error when executing `utilities/print_schema`: `Error generating schema: Postgres error: expected 0 parameters but got 1`.

I'm using PostgreSQL 16. Could this be a version compatibility issue?

**Comment by novacrazy** [comment]
I’ve refactored things a lot recently so it’s probably just a small mistake. I might not have time to diagnose it today but I’ll fix it ASAP. Thorn is still very beta, mostly for internal use in Lantern right now, but I appreciate the interest and will try to clean it up for real use.

**Comment by novacrazy** [comment]
I think I've fixed the issue, and I've tried to improve schema generation a bit while I was at it. Formatting of the generated code could use work, but still. 

I also included the `print_schema` binary in thorn itself now, as opposed to the version in Lantern which was technically under Lantern's non-commercial license. Let me know if you have any trouble using it.

**Comment by mongris** [comment]
WOW cool! I am learning Rust and using it to build a personal bot... So Im not worried about license. Thank you so much for your generosity!

**Comment by mongris** [comment]
I tried it and it works thanks!
